application: jsa-pore
version: test
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- warmup

default_expiration: 0

handlers:
- url: /a/\d+/(.+/.+)
  # must not overlap with error_handlers
  static_files: assets/\1
  upload: assets/.+/.+
  expiration: 28d

- url: /favicon.ico
  static_files: assets/img/pore.ico
  upload: assets/img/pore.ico
  expiration: 7d

- url: /fb-channel.html
  static_files: assets/fb-channel.html
  upload: assets/fb-channel.html
  expiration: 7d

- url: /.*
  script: main.app

libraries:
- name: django
  version: "1.4"

error_handlers:
- file: assets/error.html

skip_files: |
 ^(.*/)?(
 (\..*)
 |(.*\.(md|pyc))
 |((pore|ui)/.*\.(js|less))
 |(testdata)
 |(tmp)
 )$
